batch_size: 256 #512
epochs: 80
eval_every_n_epochs: 1
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
T_max_decrease: 1

#fine_tune_from: None
#epoch_warmup: 10

fine_tune_from: exp_2_STL
epoch_warmup: 0

model:
  out_dim: 256
  base_model: "vgg19"

dataset:
  dataset_type: STL10
  dataset_params:
    s: 1
    input_shape: (96,96,3)
    num_workers: 16
    valid_size: 0.05
    train_params:
      pass
    val_params:
      pass

loss:
  temperature: 0.5
  use_cosine_similarity: True
