batch_size: 256
epochs: 80
eval_every_n_epochs: 1
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False

T_max_decrease: 10

fine_tune_from: None
epoch_warmup: 1

model:
  out_dim: 256
  base_model: "vgg19"

dataset:
  dataset_type: MOOD
  dataset_params:
    s: 1
    input_shape: (96,96,3)
    num_workers: 16
    valid_size: 0.05
    train:
      - image_root: # PATH to BRAIN slices along axis 0
        folds_path: # PATH to BRIAN' .cvs file with fold cross validation index
        fold: 0
        split: train
        channels3: True
        return_image_name: True

      - image_root: # PATH to BRAIN slices along axis 1
        folds_path: # PATH to BRIAN' .cvs file with fold cross validation index
        fold: 0
        split: train
        channels3: True
        return_image_name: True
          
      - image_root: # PATH to BRAIN slices along axis 2
        folds_path: # PATH to BRIAN' .cvs file with fold cross validation index
        fold: 0
        split: train
        channels3: True
        return_image_name: True

      - image_root: # PATH to ABDOMEN slices along axis 0
        folds_path: # PATH to ABDOMEN' .cvs file with fold cross validation index
        fold: 0
        split: train
        channels3: True
        return_image_name: True

      - image_root: # PATH to ABDOMEN slices along axis 1
        folds_path: # PATH to ABDOMEN' .cvs file with fold cross validation index
        fold: 0
        split: train
        channels3: True
        return_image_name: True
          
      - image_root: # PATH to ABDOMEN slices along axis 2
        folds_path: # PATH to ABDOMEN' .cvs file with fold cross validation index
        fold: 0
        split: train
        channels3: True
        return_image_name: True
        
    val:
      - image_root: # PATH to BRAIN slices along axis 0
        folds_path: # PATH to BRIAN' .cvs file with fold cross validation index
        fold: 0
        split: val
        channels3: True
        return_image_name: True

      - image_root: # PATH to BRAIN slices along axis 1
        folds_path: # PATH to BRIAN' .cvs file with fold cross validation index
        fold: 0
        split: val
        channels3: True
        return_image_name: True
          
      - image_root: # PATH to BRAIN slices along axis 2
        folds_path: # PATH to BRIAN' .cvs file with fold cross validation index
        fold: 0
        split: val
        channels3: True
        return_image_name: True

      - image_root: # PATH to ABDOMEN slices along axis 0
        folds_path: # PATH to ABDOMEN' .cvs file with fold cross validation index
        fold: 0
        split: val
        channels3: True
        return_image_name: True

      - image_root: # PATH to ABDOMEN slices along axis 1
        folds_path: # PATH to ABDOMEN' .cvs file with fold cross validation index
        fold: 0
        split: val
        channels3: True
        return_image_name: True
          
      - image_root: # PATH to ABDOMEN slices along axis 2
        folds_path: # PATH to ABDOMEN' .cvs file with fold cross validation index
        fold: 0
        split: val
        channels3: True
        return_image_name: True

loss:
  temperature: 0.5
  use_cosine_similarity: True
